name: Deploy Azure Storage
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy ARM Template
      run: az deployment group create --resource-group devops-rg --template-file templates/storage-arm.json --parameters @templates/dev.parameters.json
    - name: Deploy Bicep Template
      run: az deployment group create --resource-group devops-rg --template-file templates/storage-bicep.bicep --parameters @templates/dev.parameters.bicep.json
