name: Deploy Azure Storage
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Make sure AZURE_CREDENTIALS is set in your repository secrets:
        # GitHub > Settings > Secrets and variables > Actions > New repository secret > Name: AZURE_CREDENTIALS
    - name: Deploy Bicep
      run: az deployment group create -g demo-rg -f templates/storage-bicep.bicep
